---
title: "PowerConsumptionAnalysis"
author: "hongyuatcufe"
date: "2021年5月19日"
output: html_document
---

## download dataset
```{r setup, include=FALSE}
download.file('https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip',destfile = 'PowerConsumption.zip',method = 'curl')
unzip('PowerConsumption.zip')
```

## import dataset with 

You can also embed plots, for example:

```{r}
library(data.table)
library(tidyverse)
library(lubridate)
PowerConsumption<-fread('household_power_consumption.txt')
### deal with Date
PowerConsumption$Date<-dmy(PowerConsumption$Date)
### rm origin file to save space
file.remove(c('household_power_consumption.txt','PowerConsumption.zip'))

```

## filter obs and export to csv
```{r}
### keep obs that dates 2007-02-01 and 2007-02-02
dataset<-filter(PowerConsumption,Date=='2007-02-01' | Date=='2007-02-02')
### remove origin dataset to save memory
rm(PowerConsumption)
### have a look at dataset
write.csv(dataset,'dataset.csv')
```

## import subset csv file and make plots
```{r}
dataset<-fread('dataset.csv')
### Plot1
png('Plot1.png',width = 480, height = 480, units='px')
with(dataset,
     hist(Global_active_power,
          col='red',
          main='Global Active Power',
          xlab='Global Active Power (kilowatts)',
          ylab='Frequency'))

dev.off()

```

```{r}
### Plot2
png('Plot2.png',width = 480, height = 480, units='px')
dataset$datetime<-ymd_hms(paste(dataset$Date,dataset$Time))
plot(dataset$datetime,dataset$Global_active_power,
     type='l',
     xlab='',
     ylab='Global Active Power (kilowatt)')
dev.off()

```


```{r}
### Plot3
png('Plot3.png',width = 480, height = 480, units='px')

plot(dataset$datetime,dataset$Sub_metering_1,
     type='n',
     xlab='',
     ylab='Energy sub metering')
lines(dataset$datetime,dataset$Sub_metering_1,col='black')
lines(dataset$datetime,dataset$Sub_metering_2,col='red')
lines(dataset$datetime,dataset$Sub_metering_3,col='blue')
legend('topright', col = c('black', 'red', 'blue'), legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lwd = 1)

dev.off()

```