---
title: "run_analysis.Rmd"
author: "hongyuatcufe"
date: "2021年5月8日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download and unzip the data

### Download dataset

```{r}
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip',destfile = 'dataset.zip',method = 'curl')
```

### Unzip dataset

```{r}
# unzip('dataset.zip',list=T)
unzip('dataset.zip')
```


## Merge dataset

```{r}
library(data.table)
testx=fread('UCI HAR Dataset/test/X_test.txt')
trainx=fread('UCI HAR Dataset/train/X_train.txt')
testy=fread('UCI HAR Dataset/test/y_test.txt')
trainy=fread('UCI HAR Dataset/train/y_train.txt')
train_subj=fread('UCI HAR Dataset/train/subject_train.txt')
test=cbind(testx,testy,0)
train=cbind(trainx,trainy,train_subj)

varnames=fread('UCI HAR Dataset/features.txt')[[2]]
names(test)=c(varnames,'activity','subject')
names(train)=c(varnames,'activity','subject')
test[['group']]='test'
train[['group']]='train'
merged_df=rbind(test,train)

```

## Extract the mean and std variables

```{r}
library(dplyr)
keep=grep('(mean|std)\\(',varnames,value=T)
keep=c(keep,'group','activity','subject')
extracted_df=merged_df[,..keep]

```

## rename variable names and activity value label

```{r}
# rename activity value
extracted_df$activity=factor(
  recode(extracted_df$activity,
         `1`='WALKING',
         `2`='WALKING_UPSTAIRS',
         `3`='WALKING_DOWNSTAIRS',
         `4`='SITTING',
         `5`='STANDING',
         `6`='LAYING'),
  levels = c('WALKING','WALKING_UPSTAIRS','WALKING_DOWNSTAIRS','SITTING','STANDING','LAYING'))

# rename variable name
new_names=gsub('\\(|\\)','',names(extracted_df))
new_names=sub('^t','time_',new_names)
new_names=sub('^f','freq_',new_names)
new_names=gsub('-','_',new_names)
new_names=gsub('BodyBody','Body',new_names)
new_names=gsub('([A-Z])','_\\1',new_names)
new_names=gsub('__','_',new_names)
new_names=tolower(new_names)
names(extracted_df)=new_names
names(extracted_df)
head(extracted_df,5)
write.csv(extracted_df,'data.csv')

```

## creates a second, independent tidy data set with the average of each variable for each activity and each subject.

```{r message=FALSE, warning=FALSE}
extracted_mean_df=extracted_df %>% 
  group_by(activity,subject) %>% 
  summarise_all(function(x) mean(x,na.rm=T))

head(extracted_mean_df,5)
write.csv(extracted_mean_df,'data_mean.csv')
write.table(extracted_mean_df,'data_mean.txt',row.name=FALSE)
```

