---
title: "R Programming Week2 Assignment"
output: html_notebook
---

```{r}
#setwd('RprogrammingWeek2')
pollutantmean<-function(directory,pollutant,id=1:332){
    total_data=data.frame()
    for (i in id) {
        total_data=rbind(total_data,read.csv(paste(directory,'/',formatC(i,width=3,flag='0'),'.csv',sep='')))
    }
    mean(total_data[[pollutant]],na.rm=T)
}

complete<-function(directory,id=1:332){
    result_df=data.frame()
    for (i in id){
        temp_data=read.csv(paste(directory,'/',formatC(i,width=3,flag='0'),'.csv',sep=''))
        nobs=sum(apply(!is.na(temp_data),1,all))
        result_df=rbind(result_df,data.frame(id=i,nobs=sum(apply(!is.na(temp_data),1,all))))
    }
    result_df
}

corr<-function(directory,threshold=0){
    corr_vec=c()
    id=1:332
    for (i in id){
        temp_data=read.csv(paste(directory,'/',formatC(i,width=3,flag='0'),'.csv',sep=''))
        nobs=sum(apply(!is.na(temp_data),1,all))
        if (nobs>threshold){
            corr_vec=c(corr_vec,with(temp_data,cor(sulfate,nitrate,use='complete')))
        }
    }
    corr_vec
}

```

Test pollutantmean function
```{r}
pollutantmean("specdata", "sulfate", 1:10)
pollutantmean("specdata", "nitrate", 70:72)
pollutantmean("specdata", "nitrate", 23)
```

Test complete function
```{r}
complete("specdata", 1)
complete("specdata", c(2, 4, 8, 10, 12))
complete("specdata", 30:25)
complete("specdata", 3)
```

Test corr function

```{r}
cr <- corr("specdata", 150)
head(cr)
summary(cr)
cr <- corr("specdata", 400)
head(cr)
summary(cr)
cr <- corr("specdata", 5000)
summary(cr)
length(cr)
cr <- corr("specdata")
summary(cr)
length(cr)

```